### ISSUE TITLE
Warnings in api call, process hangs up

### ISSUE THREAD

**Issue by roynalnaruto** [krunkosaurus/bettertouchtool-crypto#3]
Hello @krunkosaurus ! I love this project. Thanks for it. But I noticed, "coinbase" now ask you to also provide api version in the headers (otherwise it throws an error). Even after it adding it, it sometimes throws warnings in the response, due to which results are not as per required. I am suggesting the following changes, that I made to get it working.
```
set json to do shell script "curl -H 'CB-VERSION: 2015-04-08' https://api.coinbase.com/v2/prices/BTC-USD/spot"
set json to do shell script "sed s/warnings.*//g <<< " & json
set value to do shell script "sed s/[a-zA-Z:{},]//g <<< " & json
return "$" & value
```
Have a look at the regex to remove everything after "warnings", and added header in the curl request. Please update your jsons as per. Thanks for this project!

**Comment by krunkosaurus** [comment]
I have rolled your changes into master. Thanks @roynalnaruto!
